### ISSUE TITLE
OAuth not loading/login not working

### ISSUE THREAD

**Issue by Smirkybec** [hatnote/monumental-wlm#28]
Uploads seemed to be working yesterday, but today the OAuth extension doesn't seem to be loading (it is working elsewhere). It is impossible to log in and upload, as it is stuck saying just "Loading" both on the main screen in the top right corner, and in the individual monument upload windows.

**Comment by mahmoud** [comment]
@Smirkybec Great catch! Looks like that regressed while I was deploying some 2021 changes Friday night. Redeployed, restarted, and it seems to be working now. Thank you!

**Comment by Smirkybec** [comment]
Oh brilliant! Thank you so much for letting me know, hugely appreciated!
