### ISSUE TITLE
2023 update?

### ISSUE THREAD

**Issue by Smirkybec** [hatnote/monumental-wlm#54]
I don't know if this is a shot in the dark, but is there anyone prepared to update Monumental to point to the 2023 categories etc? Ireland is dependant on this tool for WLM, so would be good to know one way or another ASAP.

**Comment by Smirkybec** [comment]
Thank you so much Mahmoud! I really appreciate it!

**Comment by mahmoud** [comment]
OK, I just updated https://maps.wikilovesmonuments.org/

After a brief clicking around, seems to be working just fine. Let us know if there are any more issues.
